import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from '../server/app.js';
import {demoPlan} from '../shared/plan.js';
async function run(options,fn){const server=createApp(options).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{await fn(`http://127.0.0.1:${server.address().port}`);}finally{await new Promise(r=>server.close(r));}}
const post=(url,body)=>fetch(url+'/api/generate-video-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
test('missing configuration and invalid input return actionable errors',()=>run({apiKey:'',demo:false},async url=>{assert.equal((await post(url,{prompt:'x',mode:'image'})).status,503);assert.equal((await post(url,{prompt:' ',mode:'image'})).status,400);assert.equal((await post(url,{prompt:'x',mode:'bad'})).status,400);assert.equal((await fetch(url+'/.env')).status,404);}));
test('both demo modes return valid plans and explicit provider',async()=>{for(const mode of ['image','html'])await run({demo:true},async url=>{const r=await post(url,{prompt:'水循环',mode});const j=await r.json();assert.equal(r.status,200);assert.equal(j.provider,'demo');assert.equal(j.data.quiz_cards.length,3);assert.equal(j.data.video.mode,mode);});});
test('OpenAI request uses strict schema; success propagates dynamic content',()=>run({demo:false,client:{responses:{parse:async args=>{assert.equal(args.text.format.strict,true);assert.equal(args.store,false);assert.equal(args.input,'水循环');return {status:'completed',output_parsed:demoPlan('水循环','html')};}}}},async url=>{const r=await post(url,{prompt:'水循环',mode:'html'});assert.equal(r.status,200);assert.equal((await r.json()).provider,'openai');}));
test('reject invalid quiz counts, ordering, duration and incomplete responses',async()=>{for(const mutate of [p=>p.quiz_cards.pop(),p=>p.scenes[0].index=9,p=>p.video.total_duration_seconds=99]){const plan=demoPlan('topic','image');mutate(plan);await run({client:{responses:{parse:async()=>({status:'completed',output_parsed:plan})}}},async url=>assert.equal((await post(url,{prompt:'x',mode:'image'})).status,502));}await run({client:{responses:{parse:async()=>({status:'incomplete'})}}},async url=>assert.equal((await post(url,{prompt:'x',mode:'image'})).status,502));});
test('refusal, timeout, malformed JSON and cross-origin requests are handled',async()=>{for(const [reply,status] of [[async()=>({status:'completed',output:[{type:'message',content:[{type:'refusal'}]}]}),422],[async()=>{throw Object.assign(new Error('private'),{name:'TimeoutError'});},504]])await run({client:{responses:{parse:reply}}},async url=>assert.equal((await post(url,{prompt:'x',mode:'image'})).status,status));await run({demo:true},async url=>{assert.equal((await fetch(url+'/api/generate-video-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:'{'})).status,400);assert.equal((await fetch(url+'/api/health',{headers:{Origin:'https://untrusted.example'}})).status,403);});});
test('concurrent generation is rejected and lock is released',()=>{let release;const pending=new Promise(r=>release=r);return run({client:{responses:{parse:async()=>{await pending;return {status:'completed',output_parsed:demoPlan('x','image')};}}}},async url=>{const first=post(url,{prompt:'x',mode:'image'});await new Promise(r=>setTimeout(r,30));assert.equal((await post(url,{prompt:'x',mode:'image'})).status,429);release();assert.equal((await first).status,200);assert.equal((await post(url,{prompt:'x',mode:'image'})).status,200);});});
test('DeepSeek JSON output request and validation',async()=>{
 for(const mode of ['image','html'])await run({provider:'deepseek',client:{chat:{completions:{create:async args=>{assert.equal(args.response_format.type,'json_object');assert.equal(args.model,'deepseek-flash');assert.match(args.messages[0].content,/JSON Schema/);return {choices:[{finish_reason:'stop',message:{content:JSON.stringify(demoPlan('水循环',mode))}}]};}}}}},async url=>{const r=await post(url,{prompt:'水循环',mode});assert.equal(r.status,200);assert.equal((await r.json()).provider,'deepseek');});
 for(const content of ['', '{bad',JSON.stringify({...demoPlan('x','image'),quiz_cards:[]})])await run({provider:'deepseek',client:{chat:{completions:{create:async()=>({choices:[{finish_reason:'stop',message:{content}}]})}}}},async url=>assert.equal((await post(url,{prompt:'x',mode:'image'})).status,502));
});
test('DeepSeek missing key does not fall back to OpenAI',()=>run({provider:'deepseek',apiKey:'',demo:false},async url=>{const r=await post(url,{prompt:'x',mode:'image'});assert.equal(r.status,503);assert.match((await r.json()).error,/DEEPSEEK_API_KEY/);}));
